env:
  global:
    - CC_TEST_REPORTER_ID=8fc447cbfa7e3d560a9cc96508c3c185f2e8d212104a5fc61b2d026314ddf88c
cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - 5
  - 6
  - 7
  - 8
matrix:
  - NPM_VERSION=5
before_install:
  - npm i -g npm@$NPM_VERSION
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
